'use strict';

module.exports = {
    DEFAULT_INITIAL_SIZE: (8 * 1024),
    DEFAULT_INCREMENT_AMOUNT: (16 * 1024),
    DEFAULT_MAX_SIZE: (32 * 1024),
    //DEFAULT_FREQUENCY: 1,
    //DEFAULT_CHUNK_SIZE: 1024,
    //DEFAULT_PULL_USED_PROC: 30,
    DEFAULT_TMP_DIR: '.'
};